force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Partial Hours</fullName>
            </value>
            <value>
                <fullName>Soft Close</fullName>
            </value>
            <value>
                <fullName>Hard Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location_Daily_Info__c/Location_Daily_Info__c.object-meta.xml
<CustomObject>
    <label>Location Daily Info</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Location Daily Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Location Daily Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Location_Daily_Info__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Location Daily Info</relationshipLabel>
    <relationshipName>Location_Daily_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Daily_Info__c/fields/Seats_Available_Afternoon__c.field-meta.xml
<CustomField>
    <fullName>Seats_Available_Afternoon__c</fullName>
    <label>Seats Available Afternoon</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location_Daily_Info__c/fields/Seats_Available_Full__c.field-meta.xml
<CustomField>
    <fullName>Seats_Available_Full__c</fullName>
    <formula>IF ( Seats_Available_Morning__c  = 0 ||   Seats_Available_Afternoon__c   = 0, 0 ,

IF(Seats_Available_Morning__c &lt;= Seats_Available_Afternoon__c , Seats_Available_Morning__c, Seats_Available_Afternoon__c)

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Seats Available Full</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Location_Daily_Info__c/fields/Seats_Available_Morning__c.field-meta.xml
<CustomField>
    <fullName>Seats_Available_Morning__c</fullName>
    <label>Seats Available Morning</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LocationStatusController.cls
public with sharing class LocationStatusController {
    
    @AuraEnabled(cacheable=true)
    public static List<Location__c> getLocations(){
        return [SELECT Id, Name, City__c, Status__c FROM Location__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<Location_Daily_Info__c> getLocationDates(String location){
        return [SELECT Date__c, Id, Location__c, Seats_Available_Full__c, Seats_Available_Afternoon__c,Seats_Available_Morning__c FROM Location_Daily_Info__c WHERE Location__c = :location AND Date__c != null AND Date__c >= TODAY ORDER BY Date__c];
    }

}